//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MedioUnicoDePago.VerificarCelu {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="VerificaMailCelularSoap", Namespace="http://anses.gov.ar/arquitectura/")]
    public partial class VerificaMailCelular : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback VerificarMailOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarMailconCuerpoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmarMailOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmarMailxIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarCelularOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmarCelularOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmarCelularxIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public VerificaMailCelular() {
            this.Url = global::MedioUnicoDePago.Properties.Settings.Default.CunaMiAnses_VerificarCelu_VerificaMailCelular;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event VerificarMailCompletedEventHandler VerificarMailCompleted;
        
        /// <remarks/>
        public event VerificarMailconCuerpoCompletedEventHandler VerificarMailconCuerpoCompleted;
        
        /// <remarks/>
        public event ConfirmarMailCompletedEventHandler ConfirmarMailCompleted;
        
        /// <remarks/>
        public event ConfirmarMailxIdCompletedEventHandler ConfirmarMailxIdCompleted;
        
        /// <remarks/>
        public event VerificarCelularCompletedEventHandler VerificarCelularCompleted;
        
        /// <remarks/>
        public event ConfirmarCelularCompletedEventHandler ConfirmarCelularCompleted;
        
        /// <remarks/>
        public event ConfirmarCelularxIdCompletedEventHandler ConfirmarCelularxIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://anses.gov.ar/arquitectura/VerificarMail", RequestNamespace="http://anses.gov.ar/arquitectura/", ResponseNamespace="http://anses.gov.ar/arquitectura/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int VerificarMail(string Cuil, string CorreoElectronico) {
            object[] results = this.Invoke("VerificarMail", new object[] {
                        Cuil,
                        CorreoElectronico});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void VerificarMailAsync(string Cuil, string CorreoElectronico) {
            this.VerificarMailAsync(Cuil, CorreoElectronico, null);
        }
        
        /// <remarks/>
        public void VerificarMailAsync(string Cuil, string CorreoElectronico, object userState) {
            if ((this.VerificarMailOperationCompleted == null)) {
                this.VerificarMailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarMailOperationCompleted);
            }
            this.InvokeAsync("VerificarMail", new object[] {
                        Cuil,
                        CorreoElectronico}, this.VerificarMailOperationCompleted, userState);
        }
        
        private void OnVerificarMailOperationCompleted(object arg) {
            if ((this.VerificarMailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarMailCompleted(this, new VerificarMailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://anses.gov.ar/arquitectura/VerificarMailconCuerpo", RequestNamespace="http://anses.gov.ar/arquitectura/", ResponseNamespace="http://anses.gov.ar/arquitectura/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int VerificarMailconCuerpo(string Cuil, string CorreoElectronico, string CuerpoHTML) {
            object[] results = this.Invoke("VerificarMailconCuerpo", new object[] {
                        Cuil,
                        CorreoElectronico,
                        CuerpoHTML});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void VerificarMailconCuerpoAsync(string Cuil, string CorreoElectronico, string CuerpoHTML) {
            this.VerificarMailconCuerpoAsync(Cuil, CorreoElectronico, CuerpoHTML, null);
        }
        
        /// <remarks/>
        public void VerificarMailconCuerpoAsync(string Cuil, string CorreoElectronico, string CuerpoHTML, object userState) {
            if ((this.VerificarMailconCuerpoOperationCompleted == null)) {
                this.VerificarMailconCuerpoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarMailconCuerpoOperationCompleted);
            }
            this.InvokeAsync("VerificarMailconCuerpo", new object[] {
                        Cuil,
                        CorreoElectronico,
                        CuerpoHTML}, this.VerificarMailconCuerpoOperationCompleted, userState);
        }
        
        private void OnVerificarMailconCuerpoOperationCompleted(object arg) {
            if ((this.VerificarMailconCuerpoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarMailconCuerpoCompleted(this, new VerificarMailconCuerpoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://anses.gov.ar/arquitectura/ConfirmarMail", RequestNamespace="http://anses.gov.ar/arquitectura/", ResponseNamespace="http://anses.gov.ar/arquitectura/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ConfirmarMail(string Cuil, string CorreoElectronico, string Code) {
            object[] results = this.Invoke("ConfirmarMail", new object[] {
                        Cuil,
                        CorreoElectronico,
                        Code});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmarMailAsync(string Cuil, string CorreoElectronico, string Code) {
            this.ConfirmarMailAsync(Cuil, CorreoElectronico, Code, null);
        }
        
        /// <remarks/>
        public void ConfirmarMailAsync(string Cuil, string CorreoElectronico, string Code, object userState) {
            if ((this.ConfirmarMailOperationCompleted == null)) {
                this.ConfirmarMailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmarMailOperationCompleted);
            }
            this.InvokeAsync("ConfirmarMail", new object[] {
                        Cuil,
                        CorreoElectronico,
                        Code}, this.ConfirmarMailOperationCompleted, userState);
        }
        
        private void OnConfirmarMailOperationCompleted(object arg) {
            if ((this.ConfirmarMailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmarMailCompleted(this, new ConfirmarMailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://anses.gov.ar/arquitectura/ConfirmarMailxId", RequestNamespace="http://anses.gov.ar/arquitectura/", ResponseNamespace="http://anses.gov.ar/arquitectura/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ConfirmarMailxId(int IdRegistro, string Code) {
            object[] results = this.Invoke("ConfirmarMailxId", new object[] {
                        IdRegistro,
                        Code});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmarMailxIdAsync(int IdRegistro, string Code) {
            this.ConfirmarMailxIdAsync(IdRegistro, Code, null);
        }
        
        /// <remarks/>
        public void ConfirmarMailxIdAsync(int IdRegistro, string Code, object userState) {
            if ((this.ConfirmarMailxIdOperationCompleted == null)) {
                this.ConfirmarMailxIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmarMailxIdOperationCompleted);
            }
            this.InvokeAsync("ConfirmarMailxId", new object[] {
                        IdRegistro,
                        Code}, this.ConfirmarMailxIdOperationCompleted, userState);
        }
        
        private void OnConfirmarMailxIdOperationCompleted(object arg) {
            if ((this.ConfirmarMailxIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmarMailxIdCompleted(this, new ConfirmarMailxIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://anses.gov.ar/arquitectura/VerificarCelular", RequestNamespace="http://anses.gov.ar/arquitectura/", ResponseNamespace="http://anses.gov.ar/arquitectura/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int VerificarCelular(string Cuil, string Celular, int Prestador) {
            object[] results = this.Invoke("VerificarCelular", new object[] {
                        Cuil,
                        Celular,
                        Prestador});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void VerificarCelularAsync(string Cuil, string Celular, int Prestador) {
            this.VerificarCelularAsync(Cuil, Celular, Prestador, null);
        }
        
        /// <remarks/>
        public void VerificarCelularAsync(string Cuil, string Celular, int Prestador, object userState) {
            if ((this.VerificarCelularOperationCompleted == null)) {
                this.VerificarCelularOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarCelularOperationCompleted);
            }
            this.InvokeAsync("VerificarCelular", new object[] {
                        Cuil,
                        Celular,
                        Prestador}, this.VerificarCelularOperationCompleted, userState);
        }
        
        private void OnVerificarCelularOperationCompleted(object arg) {
            if ((this.VerificarCelularCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarCelularCompleted(this, new VerificarCelularCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://anses.gov.ar/arquitectura/ConfirmarCelular", RequestNamespace="http://anses.gov.ar/arquitectura/", ResponseNamespace="http://anses.gov.ar/arquitectura/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ConfirmarCelular(string Cuil, string Celular, string Code) {
            object[] results = this.Invoke("ConfirmarCelular", new object[] {
                        Cuil,
                        Celular,
                        Code});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmarCelularAsync(string Cuil, string Celular, string Code) {
            this.ConfirmarCelularAsync(Cuil, Celular, Code, null);
        }
        
        /// <remarks/>
        public void ConfirmarCelularAsync(string Cuil, string Celular, string Code, object userState) {
            if ((this.ConfirmarCelularOperationCompleted == null)) {
                this.ConfirmarCelularOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmarCelularOperationCompleted);
            }
            this.InvokeAsync("ConfirmarCelular", new object[] {
                        Cuil,
                        Celular,
                        Code}, this.ConfirmarCelularOperationCompleted, userState);
        }
        
        private void OnConfirmarCelularOperationCompleted(object arg) {
            if ((this.ConfirmarCelularCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmarCelularCompleted(this, new ConfirmarCelularCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://anses.gov.ar/arquitectura/ConfirmarCelularxId", RequestNamespace="http://anses.gov.ar/arquitectura/", ResponseNamespace="http://anses.gov.ar/arquitectura/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ConfirmarCelularxId(int IdRegistro, string Code) {
            object[] results = this.Invoke("ConfirmarCelularxId", new object[] {
                        IdRegistro,
                        Code});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmarCelularxIdAsync(int IdRegistro, string Code) {
            this.ConfirmarCelularxIdAsync(IdRegistro, Code, null);
        }
        
        /// <remarks/>
        public void ConfirmarCelularxIdAsync(int IdRegistro, string Code, object userState) {
            if ((this.ConfirmarCelularxIdOperationCompleted == null)) {
                this.ConfirmarCelularxIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmarCelularxIdOperationCompleted);
            }
            this.InvokeAsync("ConfirmarCelularxId", new object[] {
                        IdRegistro,
                        Code}, this.ConfirmarCelularxIdOperationCompleted, userState);
        }
        
        private void OnConfirmarCelularxIdOperationCompleted(object arg) {
            if ((this.ConfirmarCelularxIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmarCelularxIdCompleted(this, new ConfirmarCelularxIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void VerificarMailCompletedEventHandler(object sender, VerificarMailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarMailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarMailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void VerificarMailconCuerpoCompletedEventHandler(object sender, VerificarMailconCuerpoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarMailconCuerpoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarMailconCuerpoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConfirmarMailCompletedEventHandler(object sender, ConfirmarMailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmarMailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmarMailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConfirmarMailxIdCompletedEventHandler(object sender, ConfirmarMailxIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmarMailxIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmarMailxIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void VerificarCelularCompletedEventHandler(object sender, VerificarCelularCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarCelularCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarCelularCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConfirmarCelularCompletedEventHandler(object sender, ConfirmarCelularCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmarCelularCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmarCelularCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConfirmarCelularxIdCompletedEventHandler(object sender, ConfirmarCelularxIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmarCelularxIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmarCelularxIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591