//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedioUnicoDePago.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://labprueba3.anses.gov.ar:8080/CheckMail/VerificaMailCelular.asmx")]
        public string MedioUnicoDePago_VerificarCelu_VerificaMailCelular {
            get {
                return ((string)(this["MedioUnicoDePago_VerificarCelu_VerificaMailCelular"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ansesnegodesa19/ArgentaCWS/ArgentaCWS.asmx")]
        public string MedioUnicoDePago_ArgentaCWS_ArgentaCWS {
            get {
                return ((string)(this["MedioUnicoDePago_ArgentaCWS_ArgentaCWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ansesnegodesa19/ArgentaCWS/ArgentaCWS.asmx")]
        public string MedioUnicoDePago_ArgentaCWS_ArgentaCWS1 {
            get {
                return ((string)(this["MedioUnicoDePago_ArgentaCWS_ArgentaCWS1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ansesnegodesa19/ArgentaCWS/ArgentaCWS.asmx")]
        public string CunaMiAnses_ArgentaCWS_ArgentaCWS {
            get {
                return ((string)(this["CunaMiAnses_ArgentaCWS_ArgentaCWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://labprueba3.anses.gov.ar:8080/CheckMail/VerificaMailCelular.asmx")]
        public string CunaMiAnses_VerificarCelu_VerificaMailCelular {
            get {
                return ((string)(this["CunaMiAnses_VerificarCelu_VerificaMailCelular"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://presdesabper/serviciovalidacionCBU/ValidarCBU.asmx")]
        public string MedioUnicoDePago_validarCBU_ValidarCBU {
            get {
                return ((string)(this["MedioUnicoDePago_validarCBU_ValidarCBU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://presdesabper19/ADPLocalizacionDB2SP/DatosdePersonaporCuip.asmx")]
        public string MedioUnicoDePago_DatosdePersonaporCuip_DatosdePersonaporCuip {
            get {
                return ((string)(this["MedioUnicoDePago_DatosdePersonaporCuip_DatosdePersonaporCuip"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.8.10.124/GestionarMPU/GestionarMPU.asmx")]
        public string MedioUnicoDePago_GestionarMPU_GestionMPU {
            get {
                return ((string)(this["MedioUnicoDePago_GestionarMPU_GestionMPU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://presdesabper19/ADPWrapper/ADPWrapperWS.asmx")]
        public string MedioUnicoDePago_ADPWrapperWS_ADPWrapperWS {
            get {
                return ((string)(this["MedioUnicoDePago_ADPWrapperWS_ADPWrapperWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://labprueba3.anses.gov.ar:8080/checkmail/enviarmail.asmx")]
        public string MedioUnicoDePago_EnviarMail_EnviarMail {
            get {
                return ((string)(this["MedioUnicoDePago_EnviarMail_EnviarMail"]));
            }
        }
    }
}
