//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MedioUnicoDePago.GestionarMPU {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GestionMPUSoap", Namespace="http://MPU.anses.gov.ar")]
    public partial class GestionMPU : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultarBancosPorCercaniaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerMedioPagoVigenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarMedioPagoUnicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarMPDisponiblesOperationCompleted;
        
        private System.Threading.SendOrPostCallback TraerBancosFisicosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarBancosVirtualesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarBilleterasVirtualesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarBancosCorreoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerApoderadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerNombreBancoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerNombreAgenciaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GestionMPU() {
            this.Url = global::MedioUnicoDePago.Properties.Settings.Default.MedioUnicoDePago_GestionarMPU_GestionMPU;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultarBancosPorCercaniaCompletedEventHandler ConsultarBancosPorCercaniaCompleted;
        
        /// <remarks/>
        public event ObtenerMedioPagoVigenteCompletedEventHandler ObtenerMedioPagoVigenteCompleted;
        
        /// <remarks/>
        public event GuardarMedioPagoUnicoCompletedEventHandler GuardarMedioPagoUnicoCompleted;
        
        /// <remarks/>
        public event ListarMPDisponiblesCompletedEventHandler ListarMPDisponiblesCompleted;
        
        /// <remarks/>
        public event TraerBancosFisicosCompletedEventHandler TraerBancosFisicosCompleted;
        
        /// <remarks/>
        public event ListarBancosVirtualesCompletedEventHandler ListarBancosVirtualesCompleted;
        
        /// <remarks/>
        public event ListarBilleterasVirtualesCompletedEventHandler ListarBilleterasVirtualesCompleted;
        
        /// <remarks/>
        public event ListarBancosCorreoCompletedEventHandler ListarBancosCorreoCompleted;
        
        /// <remarks/>
        public event ObtenerApoderadoCompletedEventHandler ObtenerApoderadoCompleted;
        
        /// <remarks/>
        public event ObtenerNombreBancoCompletedEventHandler ObtenerNombreBancoCompleted;
        
        /// <remarks/>
        public event ObtenerNombreAgenciaCompletedEventHandler ObtenerNombreAgenciaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://MPU.anses.gov.ar/ConsultarBancosPorCercania", RequestNamespace="http://MPU.anses.gov.ar", ResponseNamespace="http://MPU.anses.gov.ar", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DTOBanco[] ConsultarBancosPorCercania(string codigoPostal) {
            object[] results = this.Invoke("ConsultarBancosPorCercania", new object[] {
                        codigoPostal});
            return ((DTOBanco[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarBancosPorCercaniaAsync(string codigoPostal) {
            this.ConsultarBancosPorCercaniaAsync(codigoPostal, null);
        }
        
        /// <remarks/>
        public void ConsultarBancosPorCercaniaAsync(string codigoPostal, object userState) {
            if ((this.ConsultarBancosPorCercaniaOperationCompleted == null)) {
                this.ConsultarBancosPorCercaniaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarBancosPorCercaniaOperationCompleted);
            }
            this.InvokeAsync("ConsultarBancosPorCercania", new object[] {
                        codigoPostal}, this.ConsultarBancosPorCercaniaOperationCompleted, userState);
        }
        
        private void OnConsultarBancosPorCercaniaOperationCompleted(object arg) {
            if ((this.ConsultarBancosPorCercaniaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarBancosPorCercaniaCompleted(this, new ConsultarBancosPorCercaniaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://MPU.anses.gov.ar/ObtenerMedioPagoVigente", RequestNamespace="http://MPU.anses.gov.ar", ResponseNamespace="http://MPU.anses.gov.ar", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DTOMedioPagoVigente ObtenerMedioPagoVigente(string cuil) {
            object[] results = this.Invoke("ObtenerMedioPagoVigente", new object[] {
                        cuil});
            return ((DTOMedioPagoVigente)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerMedioPagoVigenteAsync(string cuil) {
            this.ObtenerMedioPagoVigenteAsync(cuil, null);
        }
        
        /// <remarks/>
        public void ObtenerMedioPagoVigenteAsync(string cuil, object userState) {
            if ((this.ObtenerMedioPagoVigenteOperationCompleted == null)) {
                this.ObtenerMedioPagoVigenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerMedioPagoVigenteOperationCompleted);
            }
            this.InvokeAsync("ObtenerMedioPagoVigente", new object[] {
                        cuil}, this.ObtenerMedioPagoVigenteOperationCompleted, userState);
        }
        
        private void OnObtenerMedioPagoVigenteOperationCompleted(object arg) {
            if ((this.ObtenerMedioPagoVigenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerMedioPagoVigenteCompleted(this, new ObtenerMedioPagoVigenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://MPU.anses.gov.ar/GuardarMedioPagoUnico", RequestNamespace="http://MPU.anses.gov.ar", ResponseNamespace="http://MPU.anses.gov.ar", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GuardarMedioPagoUnico(DTOMedioPago medioPago) {
            object[] results = this.Invoke("GuardarMedioPagoUnico", new object[] {
                        medioPago});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarMedioPagoUnicoAsync(DTOMedioPago medioPago) {
            this.GuardarMedioPagoUnicoAsync(medioPago, null);
        }
        
        /// <remarks/>
        public void GuardarMedioPagoUnicoAsync(DTOMedioPago medioPago, object userState) {
            if ((this.GuardarMedioPagoUnicoOperationCompleted == null)) {
                this.GuardarMedioPagoUnicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarMedioPagoUnicoOperationCompleted);
            }
            this.InvokeAsync("GuardarMedioPagoUnico", new object[] {
                        medioPago}, this.GuardarMedioPagoUnicoOperationCompleted, userState);
        }
        
        private void OnGuardarMedioPagoUnicoOperationCompleted(object arg) {
            if ((this.GuardarMedioPagoUnicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarMedioPagoUnicoCompleted(this, new GuardarMedioPagoUnicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://MPU.anses.gov.ar/ListarMPDisponibles", RequestNamespace="http://MPU.anses.gov.ar", ResponseNamespace="http://MPU.anses.gov.ar", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DTOMedioPagoDisponible[] ListarMPDisponibles(string cuil) {
            object[] results = this.Invoke("ListarMPDisponibles", new object[] {
                        cuil});
            return ((DTOMedioPagoDisponible[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarMPDisponiblesAsync(string cuil) {
            this.ListarMPDisponiblesAsync(cuil, null);
        }
        
        /// <remarks/>
        public void ListarMPDisponiblesAsync(string cuil, object userState) {
            if ((this.ListarMPDisponiblesOperationCompleted == null)) {
                this.ListarMPDisponiblesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarMPDisponiblesOperationCompleted);
            }
            this.InvokeAsync("ListarMPDisponibles", new object[] {
                        cuil}, this.ListarMPDisponiblesOperationCompleted, userState);
        }
        
        private void OnListarMPDisponiblesOperationCompleted(object arg) {
            if ((this.ListarMPDisponiblesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarMPDisponiblesCompleted(this, new ListarMPDisponiblesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://MPU.anses.gov.ar/TraerBancosFisicos", RequestNamespace="http://MPU.anses.gov.ar", ResponseNamespace="http://MPU.anses.gov.ar", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DTOBanco[] TraerBancosFisicos(short codigoPostal) {
            object[] results = this.Invoke("TraerBancosFisicos", new object[] {
                        codigoPostal});
            return ((DTOBanco[])(results[0]));
        }
        
        /// <remarks/>
        public void TraerBancosFisicosAsync(short codigoPostal) {
            this.TraerBancosFisicosAsync(codigoPostal, null);
        }
        
        /// <remarks/>
        public void TraerBancosFisicosAsync(short codigoPostal, object userState) {
            if ((this.TraerBancosFisicosOperationCompleted == null)) {
                this.TraerBancosFisicosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraerBancosFisicosOperationCompleted);
            }
            this.InvokeAsync("TraerBancosFisicos", new object[] {
                        codigoPostal}, this.TraerBancosFisicosOperationCompleted, userState);
        }
        
        private void OnTraerBancosFisicosOperationCompleted(object arg) {
            if ((this.TraerBancosFisicosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraerBancosFisicosCompleted(this, new TraerBancosFisicosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://MPU.anses.gov.ar/ListarBancosVirtuales", RequestNamespace="http://MPU.anses.gov.ar", ResponseNamespace="http://MPU.anses.gov.ar", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DTOBanco[] ListarBancosVirtuales() {
            object[] results = this.Invoke("ListarBancosVirtuales", new object[0]);
            return ((DTOBanco[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarBancosVirtualesAsync() {
            this.ListarBancosVirtualesAsync(null);
        }
        
        /// <remarks/>
        public void ListarBancosVirtualesAsync(object userState) {
            if ((this.ListarBancosVirtualesOperationCompleted == null)) {
                this.ListarBancosVirtualesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarBancosVirtualesOperationCompleted);
            }
            this.InvokeAsync("ListarBancosVirtuales", new object[0], this.ListarBancosVirtualesOperationCompleted, userState);
        }
        
        private void OnListarBancosVirtualesOperationCompleted(object arg) {
            if ((this.ListarBancosVirtualesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarBancosVirtualesCompleted(this, new ListarBancosVirtualesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://MPU.anses.gov.ar/ListarBilleterasVirtuales", RequestNamespace="http://MPU.anses.gov.ar", ResponseNamespace="http://MPU.anses.gov.ar", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DTOBanco[] ListarBilleterasVirtuales() {
            object[] results = this.Invoke("ListarBilleterasVirtuales", new object[0]);
            return ((DTOBanco[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarBilleterasVirtualesAsync() {
            this.ListarBilleterasVirtualesAsync(null);
        }
        
        /// <remarks/>
        public void ListarBilleterasVirtualesAsync(object userState) {
            if ((this.ListarBilleterasVirtualesOperationCompleted == null)) {
                this.ListarBilleterasVirtualesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarBilleterasVirtualesOperationCompleted);
            }
            this.InvokeAsync("ListarBilleterasVirtuales", new object[0], this.ListarBilleterasVirtualesOperationCompleted, userState);
        }
        
        private void OnListarBilleterasVirtualesOperationCompleted(object arg) {
            if ((this.ListarBilleterasVirtualesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarBilleterasVirtualesCompleted(this, new ListarBilleterasVirtualesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://MPU.anses.gov.ar/ListarBancosCorreo", RequestNamespace="http://MPU.anses.gov.ar", ResponseNamespace="http://MPU.anses.gov.ar", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DTOBanco[] ListarBancosCorreo(short codigoPostal) {
            object[] results = this.Invoke("ListarBancosCorreo", new object[] {
                        codigoPostal});
            return ((DTOBanco[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarBancosCorreoAsync(short codigoPostal) {
            this.ListarBancosCorreoAsync(codigoPostal, null);
        }
        
        /// <remarks/>
        public void ListarBancosCorreoAsync(short codigoPostal, object userState) {
            if ((this.ListarBancosCorreoOperationCompleted == null)) {
                this.ListarBancosCorreoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarBancosCorreoOperationCompleted);
            }
            this.InvokeAsync("ListarBancosCorreo", new object[] {
                        codigoPostal}, this.ListarBancosCorreoOperationCompleted, userState);
        }
        
        private void OnListarBancosCorreoOperationCompleted(object arg) {
            if ((this.ListarBancosCorreoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarBancosCorreoCompleted(this, new ListarBancosCorreoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://MPU.anses.gov.ar/ObtenerApoderado", RequestNamespace="http://MPU.anses.gov.ar", ResponseNamespace="http://MPU.anses.gov.ar", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal ObtenerApoderado(DTOApoderado apod) {
            object[] results = this.Invoke("ObtenerApoderado", new object[] {
                        apod});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerApoderadoAsync(DTOApoderado apod) {
            this.ObtenerApoderadoAsync(apod, null);
        }
        
        /// <remarks/>
        public void ObtenerApoderadoAsync(DTOApoderado apod, object userState) {
            if ((this.ObtenerApoderadoOperationCompleted == null)) {
                this.ObtenerApoderadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerApoderadoOperationCompleted);
            }
            this.InvokeAsync("ObtenerApoderado", new object[] {
                        apod}, this.ObtenerApoderadoOperationCompleted, userState);
        }
        
        private void OnObtenerApoderadoOperationCompleted(object arg) {
            if ((this.ObtenerApoderadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerApoderadoCompleted(this, new ObtenerApoderadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://MPU.anses.gov.ar/ObtenerNombreBanco", RequestNamespace="http://MPU.anses.gov.ar", ResponseNamespace="http://MPU.anses.gov.ar", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerNombreBanco(short banco) {
            object[] results = this.Invoke("ObtenerNombreBanco", new object[] {
                        banco});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerNombreBancoAsync(short banco) {
            this.ObtenerNombreBancoAsync(banco, null);
        }
        
        /// <remarks/>
        public void ObtenerNombreBancoAsync(short banco, object userState) {
            if ((this.ObtenerNombreBancoOperationCompleted == null)) {
                this.ObtenerNombreBancoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerNombreBancoOperationCompleted);
            }
            this.InvokeAsync("ObtenerNombreBanco", new object[] {
                        banco}, this.ObtenerNombreBancoOperationCompleted, userState);
        }
        
        private void OnObtenerNombreBancoOperationCompleted(object arg) {
            if ((this.ObtenerNombreBancoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerNombreBancoCompleted(this, new ObtenerNombreBancoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://MPU.anses.gov.ar/ObtenerNombreAgencia", RequestNamespace="http://MPU.anses.gov.ar", ResponseNamespace="http://MPU.anses.gov.ar", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DTOAgencia ObtenerNombreAgencia(short banco, short agencia) {
            object[] results = this.Invoke("ObtenerNombreAgencia", new object[] {
                        banco,
                        agencia});
            return ((DTOAgencia)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerNombreAgenciaAsync(short banco, short agencia) {
            this.ObtenerNombreAgenciaAsync(banco, agencia, null);
        }
        
        /// <remarks/>
        public void ObtenerNombreAgenciaAsync(short banco, short agencia, object userState) {
            if ((this.ObtenerNombreAgenciaOperationCompleted == null)) {
                this.ObtenerNombreAgenciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerNombreAgenciaOperationCompleted);
            }
            this.InvokeAsync("ObtenerNombreAgencia", new object[] {
                        banco,
                        agencia}, this.ObtenerNombreAgenciaOperationCompleted, userState);
        }
        
        private void OnObtenerNombreAgenciaOperationCompleted(object arg) {
            if ((this.ObtenerNombreAgenciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerNombreAgenciaCompleted(this, new ObtenerNombreAgenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MPU.anses.gov.ar")]
    public partial class DTOBanco {
        
        private string codigoField;
        
        private string nombreField;
        
        private string direccionField;
        
        private string codigoAgenciaField;
        
        private string nombreAgenciaField;
        
        private string codigoPostalField;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoAgencia {
            get {
                return this.codigoAgenciaField;
            }
            set {
                this.codigoAgenciaField = value;
            }
        }
        
        /// <remarks/>
        public string NombreAgencia {
            get {
                return this.nombreAgenciaField;
            }
            set {
                this.nombreAgenciaField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoPostal {
            get {
                return this.codigoPostalField;
            }
            set {
                this.codigoPostalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MPU.anses.gov.ar")]
    public partial class DTOAgencia {
        
        private string nombreAgenciaField;
        
        private string calleField;
        
        private string numeroCalleField;
        
        private string localidadField;
        
        /// <remarks/>
        public string NombreAgencia {
            get {
                return this.nombreAgenciaField;
            }
            set {
                this.nombreAgenciaField = value;
            }
        }
        
        /// <remarks/>
        public string Calle {
            get {
                return this.calleField;
            }
            set {
                this.calleField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroCalle {
            get {
                return this.numeroCalleField;
            }
            set {
                this.numeroCalleField = value;
            }
        }
        
        /// <remarks/>
        public string Localidad {
            get {
                return this.localidadField;
            }
            set {
                this.localidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MPU.anses.gov.ar")]
    public partial class DTOApoderado {
        
        private string cuilField;
        
        private string p_pagoField;
        
        /// <remarks/>
        public string cuil {
            get {
                return this.cuilField;
            }
            set {
                this.cuilField = value;
            }
        }
        
        /// <remarks/>
        public string p_pago {
            get {
                return this.p_pagoField;
            }
            set {
                this.p_pagoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MPU.anses.gov.ar")]
    public partial class DTOMedioPagoDisponible {
        
        private decimal cuilField;
        
        private decimal peEmisionField;
        
        private decimal peLiquidadoField;
        
        private short cBancoField;
        
        private short cAgenciaField;
        
        private short cSistemaField;
        
        private string mRetenidoField;
        
        private string mPagoField;
        
        private short cTipoLiqField;
        
        private System.Nullable<decimal> cbu1Field;
        
        private System.Nullable<decimal> cbu2Field;
        
        private string nombreBancoField;
        
        private string nombreAgenciaField;
        
        /// <remarks/>
        public decimal Cuil {
            get {
                return this.cuilField;
            }
            set {
                this.cuilField = value;
            }
        }
        
        /// <remarks/>
        public decimal PeEmision {
            get {
                return this.peEmisionField;
            }
            set {
                this.peEmisionField = value;
            }
        }
        
        /// <remarks/>
        public decimal PeLiquidado {
            get {
                return this.peLiquidadoField;
            }
            set {
                this.peLiquidadoField = value;
            }
        }
        
        /// <remarks/>
        public short CBanco {
            get {
                return this.cBancoField;
            }
            set {
                this.cBancoField = value;
            }
        }
        
        /// <remarks/>
        public short CAgencia {
            get {
                return this.cAgenciaField;
            }
            set {
                this.cAgenciaField = value;
            }
        }
        
        /// <remarks/>
        public short CSistema {
            get {
                return this.cSistemaField;
            }
            set {
                this.cSistemaField = value;
            }
        }
        
        /// <remarks/>
        public string MRetenido {
            get {
                return this.mRetenidoField;
            }
            set {
                this.mRetenidoField = value;
            }
        }
        
        /// <remarks/>
        public string MPago {
            get {
                return this.mPagoField;
            }
            set {
                this.mPagoField = value;
            }
        }
        
        /// <remarks/>
        public short CTipoLiq {
            get {
                return this.cTipoLiqField;
            }
            set {
                this.cTipoLiqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Cbu1 {
            get {
                return this.cbu1Field;
            }
            set {
                this.cbu1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Cbu2 {
            get {
                return this.cbu2Field;
            }
            set {
                this.cbu2Field = value;
            }
        }
        
        /// <remarks/>
        public string NombreBanco {
            get {
                return this.nombreBancoField;
            }
            set {
                this.nombreBancoField = value;
            }
        }
        
        /// <remarks/>
        public string NombreAgencia {
            get {
                return this.nombreAgenciaField;
            }
            set {
                this.nombreAgenciaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MPU.anses.gov.ar")]
    public partial class DTOMedioPago {
        
        private decimal cuilField;
        
        private string tipoMedioPagoField;
        
        private System.Nullable<decimal> cbuInicioField;
        
        private System.Nullable<decimal> cbuFinalField;
        
        private System.Nullable<short> cBancoField;
        
        private System.Nullable<short> cAgenciaField;
        
        private decimal peInicioPagoField;
        
        private System.Nullable<decimal> cvu1Field;
        
        private System.Nullable<decimal> cvu2Field;
        
        private string aliasField;
        
        private string ipOrigenField;
        
        private System.Nullable<decimal> udaiField;
        
        private string opeTramiteField;
        
        /// <remarks/>
        public decimal Cuil {
            get {
                return this.cuilField;
            }
            set {
                this.cuilField = value;
            }
        }
        
        /// <remarks/>
        public string TipoMedioPago {
            get {
                return this.tipoMedioPagoField;
            }
            set {
                this.tipoMedioPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> CbuInicio {
            get {
                return this.cbuInicioField;
            }
            set {
                this.cbuInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> CbuFinal {
            get {
                return this.cbuFinalField;
            }
            set {
                this.cbuFinalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> CBanco {
            get {
                return this.cBancoField;
            }
            set {
                this.cBancoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> CAgencia {
            get {
                return this.cAgenciaField;
            }
            set {
                this.cAgenciaField = value;
            }
        }
        
        /// <remarks/>
        public decimal PeInicioPago {
            get {
                return this.peInicioPagoField;
            }
            set {
                this.peInicioPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Cvu1 {
            get {
                return this.cvu1Field;
            }
            set {
                this.cvu1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Cvu2 {
            get {
                return this.cvu2Field;
            }
            set {
                this.cvu2Field = value;
            }
        }
        
        /// <remarks/>
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        public string IpOrigen {
            get {
                return this.ipOrigenField;
            }
            set {
                this.ipOrigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Udai {
            get {
                return this.udaiField;
            }
            set {
                this.udaiField = value;
            }
        }
        
        /// <remarks/>
        public string OpeTramite {
            get {
                return this.opeTramiteField;
            }
            set {
                this.opeTramiteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MPU.anses.gov.ar")]
    public partial class DTOMedioPagoVigente {
        
        private long idModoField;
        
        private decimal cuilField;
        
        private int cModoPagoField;
        
        private System.Nullable<short> cBcoField;
        
        private System.Nullable<short> cAgeField;
        
        private string cbu1Field;
        
        private string cbu2Field;
        
        private string cvu1Field;
        
        private string cvu2Field;
        
        private string aliasField;
        
        private int peDesdeField;
        
        private System.Nullable<int> peHastaField;
        
        private short cEstadoField;
        
        private System.DateTime timeEstadoField;
        
        private long idTramiteField;
        
        private System.DateTime fAltaField;
        
        private string dAgeField;
        
        private string ipOrigenField;
        
        private System.Nullable<int> udaiField;
        
        private string opeTramiteField;
        
        private System.DateTime timeTramiteField;
        
        private string dBcoField;
        
        private System.Nullable<int> codigoPostalField;
        
        private string domCalleField;
        
        /// <remarks/>
        public long IdModo {
            get {
                return this.idModoField;
            }
            set {
                this.idModoField = value;
            }
        }
        
        /// <remarks/>
        public decimal Cuil {
            get {
                return this.cuilField;
            }
            set {
                this.cuilField = value;
            }
        }
        
        /// <remarks/>
        public int CModoPago {
            get {
                return this.cModoPagoField;
            }
            set {
                this.cModoPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> CBco {
            get {
                return this.cBcoField;
            }
            set {
                this.cBcoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> CAge {
            get {
                return this.cAgeField;
            }
            set {
                this.cAgeField = value;
            }
        }
        
        /// <remarks/>
        public string Cbu1 {
            get {
                return this.cbu1Field;
            }
            set {
                this.cbu1Field = value;
            }
        }
        
        /// <remarks/>
        public string Cbu2 {
            get {
                return this.cbu2Field;
            }
            set {
                this.cbu2Field = value;
            }
        }
        
        /// <remarks/>
        public string Cvu1 {
            get {
                return this.cvu1Field;
            }
            set {
                this.cvu1Field = value;
            }
        }
        
        /// <remarks/>
        public string Cvu2 {
            get {
                return this.cvu2Field;
            }
            set {
                this.cvu2Field = value;
            }
        }
        
        /// <remarks/>
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        public int PeDesde {
            get {
                return this.peDesdeField;
            }
            set {
                this.peDesdeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PeHasta {
            get {
                return this.peHastaField;
            }
            set {
                this.peHastaField = value;
            }
        }
        
        /// <remarks/>
        public short CEstado {
            get {
                return this.cEstadoField;
            }
            set {
                this.cEstadoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TimeEstado {
            get {
                return this.timeEstadoField;
            }
            set {
                this.timeEstadoField = value;
            }
        }
        
        /// <remarks/>
        public long IdTramite {
            get {
                return this.idTramiteField;
            }
            set {
                this.idTramiteField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FAlta {
            get {
                return this.fAltaField;
            }
            set {
                this.fAltaField = value;
            }
        }
        
        /// <remarks/>
        public string DAge {
            get {
                return this.dAgeField;
            }
            set {
                this.dAgeField = value;
            }
        }
        
        /// <remarks/>
        public string IpOrigen {
            get {
                return this.ipOrigenField;
            }
            set {
                this.ipOrigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Udai {
            get {
                return this.udaiField;
            }
            set {
                this.udaiField = value;
            }
        }
        
        /// <remarks/>
        public string OpeTramite {
            get {
                return this.opeTramiteField;
            }
            set {
                this.opeTramiteField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TimeTramite {
            get {
                return this.timeTramiteField;
            }
            set {
                this.timeTramiteField = value;
            }
        }
        
        /// <remarks/>
        public string DBco {
            get {
                return this.dBcoField;
            }
            set {
                this.dBcoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CodigoPostal {
            get {
                return this.codigoPostalField;
            }
            set {
                this.codigoPostalField = value;
            }
        }
        
        /// <remarks/>
        public string DomCalle {
            get {
                return this.domCalleField;
            }
            set {
                this.domCalleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ConsultarBancosPorCercaniaCompletedEventHandler(object sender, ConsultarBancosPorCercaniaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarBancosPorCercaniaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarBancosPorCercaniaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DTOBanco[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DTOBanco[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ObtenerMedioPagoVigenteCompletedEventHandler(object sender, ObtenerMedioPagoVigenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerMedioPagoVigenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerMedioPagoVigenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DTOMedioPagoVigente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DTOMedioPagoVigente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GuardarMedioPagoUnicoCompletedEventHandler(object sender, GuardarMedioPagoUnicoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarMedioPagoUnicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarMedioPagoUnicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ListarMPDisponiblesCompletedEventHandler(object sender, ListarMPDisponiblesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarMPDisponiblesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarMPDisponiblesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DTOMedioPagoDisponible[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DTOMedioPagoDisponible[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void TraerBancosFisicosCompletedEventHandler(object sender, TraerBancosFisicosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraerBancosFisicosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraerBancosFisicosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DTOBanco[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DTOBanco[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ListarBancosVirtualesCompletedEventHandler(object sender, ListarBancosVirtualesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarBancosVirtualesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarBancosVirtualesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DTOBanco[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DTOBanco[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ListarBilleterasVirtualesCompletedEventHandler(object sender, ListarBilleterasVirtualesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarBilleterasVirtualesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarBilleterasVirtualesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DTOBanco[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DTOBanco[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ListarBancosCorreoCompletedEventHandler(object sender, ListarBancosCorreoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarBancosCorreoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarBancosCorreoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DTOBanco[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DTOBanco[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ObtenerApoderadoCompletedEventHandler(object sender, ObtenerApoderadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerApoderadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerApoderadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ObtenerNombreBancoCompletedEventHandler(object sender, ObtenerNombreBancoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerNombreBancoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerNombreBancoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ObtenerNombreAgenciaCompletedEventHandler(object sender, ObtenerNombreAgenciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerNombreAgenciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerNombreAgenciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DTOAgencia Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DTOAgencia)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591